spring.application.name=chatr

spring.datasource.url=${CHATR_LOCAL_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

chatr.api.jwtSecret=${JWT_SECRET}
chatr.api.jwtExpiration=${JWT_EXPIRATION)