spring.application.name=chatr

spring.datasource.url=${CHATR_LOCAL_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

chatr.api.jwtSecret=${JWT_SECRET}
chatr.api.jwtExpiration=${JWT_EXPIRATION}

server.address=0.0.0.0

spring.mail.host=localhost
spring.mail.port=2525
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

spring.data.redis.host=${LOCAL_REDIS_HOST}
spring.data.redis.port=${LOCAL_REDIS_PORT}
spring.data.redis.password=${LOCAL_REDIS_PASSWORD}
spring.data.redis.timeout=60000